.TH mountall 8 2009-09-07 upstart
.\"
.SH NAME
mountall \- Mount filesystems during boot
.\"
.SH SYNOPSIS
.B mountall
.RI [ OPTIONS ]...
.\"
.SH DESCRIPTION
.B mountall
reads
.BR fstab (5)
and calls
.BR fsck (8),
.BR mount (8)
and
.BR swapon (8)
in the correct order to mount filesystems once the underlying devices
have been created by
.BR udevd (8)

This is a temporary tool until
.BR init (8)
itself gains the necessary flexibility to perform this processing; you
should not rely on its behaviour.
.\"
.SH AUTHOR
Written by Scott James Remnant
.RB < scott@netsplit.com >
.\"
.SH BUGS
Report bugs at 
.RB < https://launchpad.net/ubuntu/+source/upstart/+bugs >
.\"
.SH COPYRIGHT
Copyright \(co 2009 Canonical Ltd.
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
